global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'credential-proxy'
    static_configs:
      - targets: ['app:3000']
    # Note: The actual port for the targets will be configured at container startup
    # See docker-compose environment variables for the actual port configuration 